/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AESMain;

import java.io.*; 
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb = new javax.swing.JTabbedPane();
        epanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BCipher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BOChooser = new javax.swing.JButton();
        OriginalFile = new javax.swing.JTextField();
        CKey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BDecipher = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BEChooser = new javax.swing.JButton();
        EncryptedFile = new javax.swing.JTextField();
        DKey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DMonitor = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StepsText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb.setAlignmentX(1.0F);
        tb.setAlignmentY(1.0F);

        epanel.setToolTipText("16 character Key");

        BCipher.setText("Cipher");
        BCipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCipherActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Text File");

        BOChooser.setText("Choose");
        BOChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOChooserActionPerformed(evt);
            }
        });

        CKey.setToolTipText("16 Character Key");
        CKey.setMaximumSize(new java.awt.Dimension(16, 16));

        jLabel2.setText("Enter Key");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OriginalFile, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(CKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOChooser)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BCipher)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OriginalFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BOChooser))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(BCipher)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout epanelLayout = new javax.swing.GroupLayout(epanel);
        epanel.setLayout(epanelLayout);
        epanelLayout.setHorizontalGroup(
            epanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        epanelLayout.setVerticalGroup(
            epanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb.addTab("ENCRYPT", epanel);

        BDecipher.setText("Decipher");
        BDecipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDecipherActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose Encrypted File");

        BEChooser.setText("Choose");
        BEChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEChooserActionPerformed(evt);
            }
        });

        DKey.setToolTipText("16 Character Key");
        DKey.setMaximumSize(new java.awt.Dimension(16, 16));

        jLabel4.setText("Enter Key");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EncryptedFile, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(DKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BEChooser)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(BDecipher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BEChooser))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BDecipher)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        DMonitor.setColumns(20);
        DMonitor.setRows(5);
        jScrollPane1.setViewportView(DMonitor);

        jLabel5.setText("Monitor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dpanelLayout = new javax.swing.GroupLayout(dpanel);
        dpanel.setLayout(dpanelLayout);
        dpanelLayout.setHorizontalGroup(
            dpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(dpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        dpanelLayout.setVerticalGroup(
            dpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb.addTab("DECRPYT", dpanel);

        StepsText.setColumns(20);
        StepsText.setRows(5);
        jScrollPane2.setViewportView(StepsText);

        jLabel6.setText("Monitor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tb)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOChooserActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        int returnValue = chooser.showOpenDialog(null);
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			File f = chooser.getSelectedFile();
			//System.out.println(f.getAbsolutePath());
                        OriginalFile.setText(f.getAbsolutePath());
		}     
    }//GEN-LAST:event_BOChooserActionPerformed

    private void BEChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEChooserActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        int returnValue = chooser.showOpenDialog(null);
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			File f = chooser.getSelectedFile();
			//System.out.println(f.getAbsolutePath());
                        EncryptedFile.setText(f.getAbsolutePath());
		}
    }//GEN-LAST:event_BEChooserActionPerformed

    private void BCipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCipherActionPerformed
        // TODO add your handling code here:
        StepsText.setText("");
        if(CKey.getText().length()==16 && OriginalFile.getText().length()>0){
            try{
                File f;   
                f = new File(OriginalFile.getText());
                FileReader fr=new FileReader(f);
                BufferedReader br=new BufferedReader(fr);
                String Enc="";
                int c,i=0;
                String str="";
                while((c=br.read())!=-1){
                    if(i<16)
                    {
                        str+=(char)c;
                        i++;
                    }
                    else{
                        i=0;
                        
                        AES mm= new AES( CKey.getText(),str);
                        String ns=mm.aesCipherLoop();
                        StepsText.append("\nOriginal"+str);
                        StepsText.append("\nEncrypted "+ns);
                        Enc+=ns;
                        str="";
                        str+=(char)c;
                        i++;
                    }
                }
                StepsText.append("\nRest "+str+"\nI "+i);
                if(i<=16)
                {
                    while(i<=16){
                        str+=" ";
                        i++;
                    }
                    AES mm= new AES( CKey.getText(),str);
                    String ns = mm.aesCipherLoop();
                    StepsText.append("\nOriginal"+str);
                    StepsText.append("\nEncrypted "+ns);
                    Enc+=ns;
                    
                }
                StepsText.append("\nEncrypted "+Enc);
                JFrame parentFrame1 = new JFrame();
                JFileChooser fileChooser1 = new JFileChooser();
                fileChooser1.setDialogTitle("Specify a file to save");   
                int userSelection = fileChooser1.showSaveDialog(parentFrame1);
                if (userSelection == JFileChooser.APPROVE_OPTION) {
                    File fileToSave = fileChooser1.getSelectedFile();
                    String path =fileToSave.getAbsolutePath();
                    try (FileWriter writer = new FileWriter(path+".txt");
                          BufferedWriter bw = new BufferedWriter(writer)) {
                        bw.write(Enc);
                        JOptionPane.showMessageDialog(null,"Encrypted Successfully");
                    } 
                    catch (IOException e) {
                        String Msg="Couldnot create new file";
                        JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
                    }
                } 
            }
            catch(FileNotFoundException e){ 
                String Msg="File not Found";
                JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
            }  
        }
        else if(CKey.getText().length()!=16 && OriginalFile.getText().length()==0)
        {
            String Msg="Choose File and Enter Key value";
            JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(CKey.getText().length()!=16){
            String Msg="Key Length must be 16";
            JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(OriginalFile.getText().length()==0)
        {
            String Msg="Choose File";
            JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BCipherActionPerformed

    private void BDecipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDecipherActionPerformed
        StepsText.setText("");
        if(DKey.getText().length()==16 && EncryptedFile.getText().length()>0){
            try{
                File f;   
                f = new File(EncryptedFile.getText());
                FileReader fr=new FileReader(f);
                BufferedReader br=new BufferedReader(fr);
                String Enc="";
                int c,i=0;
                String str="";
                while((c=br.read())!=-1){
                    if(i<16)
                    {
                        str+=(char)c;
                        i++;
                    }
                    else{
                        i=0;
                        AES mm= new AES( DKey.getText(),str);
                        String ns=mm.aesDecipherLoop();
                        StepsText.append("Encrypted "+str);
                        StepsText.append("\nOriginal "+ns);
                        Enc+=ns;
                        str="";
                        str+=(char)c;
                        i++;
                    }
                }
                StepsText.append("\nEncrypted "+str+"\ni "+i);
                if(i<=16)
                {
                    AES mm= new AES( DKey.getText(),str);
                    String ns=mm.aesDecipherLoop();
                    StepsText.append("Encrypted "+str);
                    StepsText.append("\nOriginal "+ns);
                    Enc+=ns;
                }
                StepsText.append("\nMainOriginal "+Enc);
                
                JFrame parentFrame = new JFrame();
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Specify a file to save");   
                int userSelection = fileChooser.showSaveDialog(parentFrame);
                if (userSelection == JFileChooser.APPROVE_OPTION) {
                    File fileToSave = fileChooser.getSelectedFile();
                    String path =fileToSave.getAbsolutePath();
                    try (FileWriter writer = new FileWriter(path+".txt");
                          BufferedWriter bw = new BufferedWriter(writer)) {
                        bw.write(Enc);
                        JOptionPane.showMessageDialog(null,"Decrypted Successfully");
                    } 
                    catch (IOException e) {
                        String Msg="Couldnot create new file";
                        JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
                    }
                }            
            }
            catch(FileNotFoundException e){ 
                String Msg="File not Found";
                JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
            }  
        }
        else if(DKey.getText().length()!=16 && EncryptedFile.getText().length()==0)
        {
            String Msg="Choose File and Enter Key value";
            JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(DKey.getText().length()!=16){
            String Msg="Key Length must be 16";
            JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(EncryptedFile.getText().length()==0)
        {
            String Msg="Choose File";
            JOptionPane.showMessageDialog(null,Msg,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BDecipherActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private   JScrollPane StepScorl=new JScrollPane(StepsText,
            JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCipher;
    private javax.swing.JButton BDecipher;
    private javax.swing.JButton BEChooser;
    private javax.swing.JButton BOChooser;
    private javax.swing.JTextField CKey;
    private javax.swing.JTextField DKey;
    public javax.swing.JTextArea DMonitor;
    private javax.swing.JTextField EncryptedFile;
    private javax.swing.JTextField OriginalFile;
    public static javax.swing.JTextArea StepsText;
    private javax.swing.JPanel dpanel;
    private javax.swing.JPanel epanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tb;
    // End of variables declaration//GEN-END:variables
}
